version: '3'

services:
  php:
    container_name: app_server
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - .:/var/www:delegated
    ports:
      - "9001:9000"
    networks:
      - backend

  nginx:
    container_name: nginx_server
    image: nginx:alpine
    networks:
      - backend
    ports:
      - "8080:80"
    volumes:
      - .:/var/www:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  database:
    container_name: database
    image: mysql:8.0.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge